export const ADD_ITEM_TO_WISH_REQUEST = 'ADD_ITEM_TO_WISH_REQUEST';
export const ADD_ITEM_TO_WISH_SUCCESS = 'ADD_ITEM_TO_WISH_SUCCESS';
export const ADD_ITEM_TO_WISH_FAILURE = 'ADD_ITEM_TO_WISH_FAILURE';

export const GET_WISH_REQUEST = 'GET_WISH_REQUEST';
export const GET_WISH_SUCCESS = 'GET_WISH_SUCCESS';
export const GET_WISH_FAILURE = 'GET_WISH_FAILURE';

export const REMOVE_WISH_ITEM_REQUEST = 'REMOVE_WISH_ITEM_REQUEST';
export const REMOVE_WISH_ITEM_SUCCESS = 'REMOVE_WISH_ITEM_SUCCESS';
export const REMOVE_WISH_ITEM_FAILURE = 'REMOVE_WISH_ITEM_FAILURE';

export const UPDATE_WISH_ITEM_REQUEST = 'UPDATE_WISH_ITEM_REQUEST';
export const UPDATE_WISH_ITEM_SUCCESS = 'UPDATE_WISH_ITEM_SUCCESS';
export const UPDATE_WISH_ITEM_FAILURE = 'UPDATE_WISH_ITEM_FAILURE';