export const VERIFY_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const VERIFY_FAILURE = 'CREATE_REVIEW_FAILURE';

export const Genterate_OTP_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const Genterate_OTP_FAILURE = 'CREATE_REVIEW_FAILURE';
